# Generated by Django 5.2.15 on 2026-07-22 15:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0001_initial'),
        ('products', '0004_product'),
        ('stock_movements', '0001_initial_stock_movements'),
        ('tenant', '0002_remove_tenant_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockmovement',
            options={},
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['tenant', 'product'], name='stkmov_tenant_product_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['tenant', 'created_at'], name='stkmov_tenant_created_at_idx'),
        ),
    ]
