# Generated by Django 5.2.15 on 2026-07-23 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_movements', '0002_add_stockmovement_indexes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockmovement',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='stockmovement',
            name='stkmov_tenant_product_idx',
        ),
        migrations.RemoveIndex(
            model_name='stockmovement',
            name='stkmov_tenant_created_at_idx',
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='reference_type',
            field=models.CharField(blank=True, choices=[('PURCHASE', 'Purchase'), ('SALE', 'Sale'), ('RETURN', 'Return'), ('ADJUSTMENT', 'Adjustment'), ('TRANSFER', 'Transfer')], max_length=20),
        ),
    ]
