# Generated by Django 6.0.7 on 2026-07-20 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='slug',
        ),
    ]
