# Generated by Django 5.2.15 on 2026-07-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_saleitem_unique_product_per_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIAL', 'Partial'), ('PAID', 'Paid')], default='UNPAID', max_length=20),
        ),
    ]
