# Generated by Django 5.2.15 on 2026-07-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_saleitem_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleitem',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIAL', 'Partial'), ('PAID', 'Paid')], default='UNPAID', max_length=20),
        ),
    ]
